import Link from "next/link";
import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const Header = () => {
  return (
    <header className="bg-blue-900 text-white py-4 px-6 shadow-md">
      <div className="container mx-auto flex justify-between items-center">
        <Link href="/" className="text-2xl font-bold">
          MyWebsite
        </Link>
        <nav className="flex space-x-6">
          <Link href="/about" className="hover:text-gray-400">
            About
          </Link>
          <Link href="/services" className="hover:text-gray-400">
            Services
          </Link>
          <Link href="/contact" className="hover:text-gray-400">
            Contact
          </Link>
        </nav>
      </div>
    </header>
  );
};

const Footer = () => {
  return (
    <footer className="bg-gray-900 text-white py-4 px-6 mt-10 text-center">
      <p>&copy; {new Date().getFullYear()} MyWebsite. All rights reserved.</p>
    </footer>
  );
};
// slots does not affect url structure
export default function RootLayout({
  children,
  revenue,
  users,
  notifications,
  login,
}: {
  children: React.ReactNode;
  revenue: React.ReactNode;
  notifications: React.ReactNode;
  users: React.ReactNode;
  login: React.ReactNode;
}) {
  const isLoggedIn = false;
  return isLoggedIn ? (
    <html lang="en">
      <body>
        <Header />
        <div className="container mx-auto p-4">{children}</div>
        <div className="container mx-auto p-4 flex ">
          {" "}
          <div className="flex flex-col space-y-4 ">
            {" "}
            <div>{revenue}</div>
            <div>{users}</div>
          </div>
          <div className="flex flex-1 space-y-4 ">{notifications}</div>
        </div>
        <Footer />
      </body>
    </html>
  ) : (
    login
  );
}
